/**
 * Payment Links page.
 *
 * Thin view over `useLinksData` (demo or live) and the shared UI kit. The
 * create-link modal shows the fee split up-front so chatters see what the
 * customer will actually pay.
 */

import { useMemo, useState } from 'react';
import { useCan } from '../../hooks/usePermission';
import { useRateCard } from '../../hooks/useRateCard';
import { useAppStore } from '../../store/appStore';
import { feeBreakdown } from '../../business/feeBreakdown';
import { formatMoney } from '../../lib/format';
import Modal from '../../components/Modal';
import { toast } from '../../components/Toast';
import {
  PageHeader, StatCard, StatGrid, Money, Pill, DateCell,
  DataTable, FilterBar, type Column,
} from '../../components/ui';
import type { PaymentLink, LinkStatus } from '../../types';
import { useLinksData } from './useLinksData';
import { useCreatorsData } from '../Creators/useCreatorsData';
import { effectiveLinkStatus, filterLinks, DEFAULT_FILTERS, type LinksFilters } from './filters';

const STATUS_TONE: Record<LinkStatus, 'ok' | 'no' | 'muted'> = {
  Paid: 'ok',
  Failed: 'no',
  Created: 'muted',
  Expired: 'muted',
};

export default function LinksPage() {
  const can = useCan();
  const { rateCard: rc } = useRateCard();
  const { links, isLoading, create, reconcile } = useLinksData();
  const { creators } = useCreatorsData();
  const linkLimits = useAppStore((s) => s.linkLimits);

  const [filters, setFilters] = useState<LinksFilters>(DEFAULT_FILTERS);
  const [createOpen, setCreateOpen] = useState(false);
  const [plCreatorId, setPlCreatorId] = useState('');
  const [plName, setPlName] = useState('');
  const [plUser, setPlUser] = useState('');
  const [plAmt, setPlAmt] = useState('');
  const [creating, setCreating] = useState(false);

  const filtered = useMemo(() => filterLinks(links, filters), [links, filters]);
  const paid = filtered.filter((l) => l.status === 'Paid');
  const conv = filtered.length ? Math.round((paid.length / filtered.length) * 100) : 0;
  const revenue = paid.reduce((s, l) => s + l.amount, 0);

  const clearFilters = () => setFilters(DEFAULT_FILTERS);

  const openCreate = () => {
    const activeCreators = creators.filter((c) => c.status !== 'paused' && c.status !== 'suspended');
    setPlCreatorId(activeCreators[0]?.id ?? '');
    setPlName(''); setPlUser(''); setPlAmt('');
    setCreateOpen(true);
  };

  const amtNum = parseFloat(plAmt) || 0;
  const amtValid = amtNum > 0;
  const belowMin = linkLimits.min != null && amtNum < linkLimits.min;
  const aboveMax = linkLimits.max != null && amtNum > linkLimits.max;
  const fb = amtValid && !belowMin && !aboveMax ? feeBreakdown(amtNum, rc) : null;

  const submit = async () => {
    const amt = parseFloat(plAmt);
    const floor = linkLimits.min ?? linkLimits.providerMin;
    if (!(amt >= floor)) { toast(`Minimum link amount is ${formatMoney(floor)}.`); return; }
    if (linkLimits.max != null && amt > linkLimits.max) {
      toast(`Maximum link amount is ${formatMoney(linkLimits.max)}.`); return;
    }
    if (!plCreatorId) { toast('Pick a creator.'); return; }
    const selected = creators.find((c) => c.id === plCreatorId);
    setCreating(true);
    try {
      const { url } = await create({
        creatorId: plCreatorId,
        creator: selected?.name ?? '',
        chatter: '',
        customerName: plName,
        customerUsername: plUser,
        amount: amt,
      });
      setCreateOpen(false);
      if (url) toast(`Hosted payment link generated: ${url}`);
      else toast('Hosted payment link generated.');
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Could not generate link.';
      toast(msg);
    } finally {
      setCreating(false);
    }
  };

  const showSplit = can('platform.view');
  const columns: Column<PaymentLink>[] = [
    { key: 'ref', header: 'Ref', render: (l) => <span className="ref">{l.id}</span> },
    { key: 'creator', header: 'Creator', render: (l) => l.creator || '—' },
    { key: 'chatter', header: 'Chatter', render: (l) => l.chatter || '—' },
    {
      key: 'customer', header: 'Customer',
      render: (l) => (
        <>
          <div className="cname">{l.customerName || '—'}</div>
          <div className="cemail">{l.customerUsername}</div>
        </>
      ),
    },
    { key: 'amount', header: 'Amount', align: 'right', render: (l) => <Money amount={l.amount} /> },
    {
      key: 'status', header: 'Status',
      render: (l) => {
        const s = effectiveLinkStatus(l);
        return <Pill tone={STATUS_TONE[s]}>{s}</Pill>;
      },
    },
    { key: 'date', header: 'Date', render: (l) => <DateCell ts={l.ts} /> },
  ];

  return (
    <div>
      <PageHeader
        eyebrow="Money in"
        title="Payment links"
        subtitle="Hosted checkout links generated by chatters. Card details never touch this system."
        actions={
          <>
            {can('commissions.manage') && (
              <button className="btn ghost" onClick={() => reconcile().then(() => toast('Reconciled.')).catch(() => toast('Reconcile failed.'))}>
                Reconcile
              </button>
            )}
            {can('links.create') && (
              <button className="btn" onClick={openCreate}>New link</button>
            )}
          </>
        }
      />

      <StatGrid>
        <StatCard label="Links" value={filtered.length} sub="in view" />
        <StatCard label="Paid" value={paid.length} sub="conversions" />
        <StatCard label="Conversion" value={`${conv}%`} sub="paid / total" />
        <StatCard label="Revenue" value={<Money amount={revenue} direction="in" emphasis />} sub="from paid links" />
      </StatGrid>

      <FilterBar>
        <select value={filters.creator} onChange={(e) => setFilters((f) => ({ ...f, creator: e.target.value }))}>
          <option value="">All creators</option>
          {[...new Set(creators.map((c) => c.name))].map((n) => <option key={n}>{n}</option>)}
        </select>
        <select value={filters.chatter} onChange={(e) => setFilters((f) => ({ ...f, chatter: e.target.value }))}>
          <option value="">All chatters</option>
          {[...new Set(links.map((l) => l.chatter).filter(Boolean) as string[])].map((n) => <option key={n}>{n}</option>)}
        </select>
        <select
          value={filters.status}
          onChange={(e) => setFilters((f) => ({ ...f, status: e.target.value as LinksFilters['status'] }))}
        >
          <option value="">All statuses</option>
          <option value="Created">Created</option>
          <option value="Paid">Paid</option>
          <option value="Failed">Failed</option>
          <option value="Expired">Expired</option>
        </select>
        <input
          type="number" placeholder="Min €" value={filters.min}
          onChange={(e) => setFilters((f) => ({ ...f, min: e.target.value }))}
          style={{ maxWidth: 100 }}
        />
        <input
          type="number" placeholder="Max €" value={filters.max}
          onChange={(e) => setFilters((f) => ({ ...f, max: e.target.value }))}
          style={{ maxWidth: 100 }}
        />
        <input
          type="date" value={filters.from}
          onChange={(e) => setFilters((f) => ({ ...f, from: e.target.value }))}
        />
        <input
          type="date" value={filters.to}
          onChange={(e) => setFilters((f) => ({ ...f, to: e.target.value }))}
        />
        <input
          type="search" placeholder="Search customer…" value={filters.search}
          onChange={(e) => setFilters((f) => ({ ...f, search: e.target.value }))}
          style={{ maxWidth: 180 }}
        />
        <button className="btn ghost" onClick={clearFilters}>Clear</button>
      </FilterBar>

      <DataTable
        columns={columns}
        rows={filtered}
        rowKey={(l) => l.id}
        isLoading={isLoading}
        emptyTitle="No links match these filters."
        emptyHint={can('links.create') ? 'Generate one from the header.' : 'Ask a chatter to generate one.'}
        footer={`Showing ${filtered.length}`}
      />

      <Modal open={createOpen} onClose={() => setCreateOpen(false)}>
        <h3>Create PPV link</h3>
        <p className="sub">
          Generates a hosted payment link. The customer pays on the provider's page — card details never touch this system.
        </p>
        <div className="field">
          <label>Creator</label>
          <select value={plCreatorId} onChange={(e) => setPlCreatorId(e.target.value)}>
            {creators.filter((c) => c.status !== 'paused' && c.status !== 'suspended').map((c) => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>
        </div>
        <div className="field">
          <label>Customer name <span className="sub" style={{ marginLeft: 4 }}>(optional)</span></label>
          <input type="text" placeholder="Display name" value={plName} onChange={(e) => setPlName(e.target.value)} />
        </div>
        <div className="field">
          <label>Customer username <span className="sub" style={{ marginLeft: 4 }}>(optional)</span></label>
          <input
            type="text" placeholder="@username" value={plUser}
            onChange={(e) => setPlUser(e.target.value)}
            onBlur={() => {
              const v = plUser.trim();
              if (v && !v.startsWith('@')) setPlUser(`@${v}`);
            }}
          />
        </div>
        <div className="field">
          <label>Amount (EUR)</label>
          <input
            type="number"
            min={linkLimits.min ?? linkLimits.providerMin}
            max={linkLimits.max ?? undefined}
            step={0.01}
            placeholder="0.00"
            value={plAmt}
            onChange={(e) => setPlAmt(e.target.value)}
          />
          <div className="sub" style={{ marginTop: 6 }}>
            {belowMin ? <span style={{ color: 'var(--red)' }}>Below the {formatMoney(linkLimits.min ?? 0)} minimum.</span>
              : aboveMax ? <span style={{ color: 'var(--red)' }}>Above the {formatMoney(linkLimits.max ?? 0)} maximum.</span>
                : [
                    linkLimits.min ? `Minimum ${formatMoney(linkLimits.min)}` : null,
                    linkLimits.max ? `Maximum ${formatMoney(linkLimits.max)}` : null,
                  ].filter(Boolean).join(' · ')}
          </div>
        </div>

        <div className="pl-fees">
          <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 10 }}>
            <span style={{ color: 'var(--muted)', fontSize: 13 }}>Fees on this link</span>
            <span
              className="pl-fee-pct"
              style={{
                color: fb
                  ? fb.effectivePct >= 18 ? 'var(--neg)'
                    : fb.effectivePct >= 15 ? 'var(--accent)'
                      : 'var(--ink)'
                  : 'var(--muted)',
              }}
            >
              {fb ? `${fb.effectivePct.toFixed(1)}%` : '—'}
            </span>
          </div>
          <div className="fee-line">
            <span>{fb ? `Platform fee (${fb.blendedPct}%)` : 'Platform fee'}</span>
            <b className="fee-val">{fb ? formatMoney(fb.blendedFee) : '—'}</b>
          </div>
          <div className="fee-line">
            <span>Fixed per transaction</span>
            <b className="fee-val">{fb ? formatMoney(fb.fixed) : '—'}</b>
          </div>
          {showSplit && fb && fb.pspPct != null ? (
            <>
              <div className="fee-line" style={{ opacity: 0.75 }}>
                <span>↳ PSP cost ({fb.pspPct}%)</span>
                <b className="fee-val">{formatMoney(fb.pspFee ?? 0)}</b>
              </div>
              <div className="fee-line" style={{ opacity: 0.75 }}>
                <span>↳ HigherPays margin ({fb.marginPct}%)</span>
                <b className="fee-val">{formatMoney(fb.marginFee ?? 0)}</b>
              </div>
            </>
          ) : null}
          <div className="fee-tot">
            <span>Total fees</span>
            <span className="fee-val">{fb ? formatMoney(fb.total) : '—'}</span>
          </div>
          <div className="fee-net">
            <span>Net to workspace</span>
            <span className="fee-val">{fb ? formatMoney(fb.net) : '—'}</span>
          </div>
        </div>

        <div className="modal-actions">
          <button className="btn ghost" onClick={() => setCreateOpen(false)}>Cancel</button>
          <button className="btn" onClick={submit} disabled={creating}>
            {creating ? 'Generating…' : 'Generate link'}
          </button>
        </div>
      </Modal>
    </div>
  );
}
