'use strict';
// The HigherPays data model. This file is the only source of truth:
// backend/migrations/001_init.sql is generated from it.
//
// Field names are camelCase here and become snake_case columns.
// Raw SQL (checks, index predicates) is written in snake_case.

const {
  entity,
  uuid, text, citext, char, bool, int, date, timestamp, jsonb, textArray, inet,
  money, numeric, percent, bigIdentity, enumOf,
} = require('./fields');

// ---------------------------------------------------------------------------
// Status vocabularies. Exported so routes and the frontend read the same list.
// ---------------------------------------------------------------------------
const USER_STATUS = ['active', 'suspended', 'invited'];
const WORKSPACE_STATUS = ['active', 'suspended', 'archived'];
const WORKSPACE_ROLE = ['workspace_admin', 'analyst', 'agent', 'account_owner'];
const ACCESS_STATUS = ['active', 'suspended'];

const ACCOUNT_STATUS = [ 'active', 'paused', 'archived'];
const CUSTOMER_SEGMENT = ['new', 'regular', 'high_value', 'vip', 'inactive', 'at_risk'];
const PRICING_MODE = ['fixed', 'open'];
// single_use dies on the first payment, or 24h after creation if nobody pays.
// reusable stays open through any number of payments until someone cancels it.
const LINK_TYPE = ['single_use', 'reusable'];
//   active     payable
//   pending    paid, waiting for the agent to complete the payment details
//   done       paid and completed
//   expired    a single_use link went unpaid past expiresAt
//   cancelled  closed by hand
//   refunded   a paid link was later reversed
const LINK_STATUS = ['active', 'pending', 'done', 'expired', 'cancelled', 'refunded'];
//   paid      the provider approved the charge
//   failed    the provider declined it
//   refunded  a paid charge was reversed, by refund or chargeback
const PAYMENT_STATUS = ['paid', 'failed', 'refunded'];
const TRANSACTION_TYPE = ['payment', 'refund', 'chargeback', 'adjustment'];
const TRANSACTION_STATUS = ['approved', 'declined', 'refunded', 'charged_back'];
const REVENUE_ENTRY_TYPE = ['sale', 'refund', 'chargeback'];
const REVENUE_ENTRY_STATUS = ['locked', 'reversed'];
const PAYEE_TYPE = ['account', 'agent', 'agency'];
const PAYOUT_STATUS = ['pending', 'approved', 'paid', 'on_hold'];
const FEE_MODEL = ['flat', 'cascade'];

const CHANNEL_TYPE = ['telegram'];

// ===========================================================================
// Global — not owned by a single workspace
// ===========================================================================

// A person who signs in. One user may belong to many workspaces.
const User = entity('users', {
  fields: {
    id:               uuid().primaryKey(),
    email:            citext().unique().notNull(),
    fullName:         text().notNull(),
    passwordHash:     text(),                  // null until the invite is accepted
    status:           enumOf(USER_STATUS).notNull().default("'active'"),
    isPlatformAdmin:  bool().notNull().default('false'),  // above every workspace, not a workspace role
    twoFactorEnabled: bool().notNull().default('false'),
    twoFactorSecret:  text(),                  // base32 TOTP seed; must stay readable to verify codes
    lastLoginAt:      timestamp(),
  },
  timestamps: 'both',
});

// Session handles. Only the hash is stored; familyId detects token reuse.
const RefreshToken = entity('refresh_tokens', {
  fields: {
    id:        uuid().primaryKey(),
    userId:    uuid().references('users').notNull(),
    familyId:  uuid().notNull().default('gen_random_uuid()'),
    tokenHash: text().unique().notNull(),
    expiresAt: timestamp().notNull(),
    revokedAt: timestamp(),
    userAgent: text(),
    ip:        inet(),
  },
  indexes: ['userId'],
  timestamps: 'created',
});



// One agency, and its settings. workspaceId elsewhere is a plain ownership
// foreign key, not a security boundary — nothing scopes queries by it.
const Workspace = entity('workspaces', {
  fields: {
    id:                uuid().primaryKey(),
    name:              text().notNull(),
    currency:          char(3).notNull().default("'EUR'"),
    status:            enumOf(WORKSPACE_STATUS).notNull().default("'active'"),

    merchantId:        text(),                 // the MID at MantaPay
    providerConfigRef: text(),                 // secret-store key name, never the secret

    // Generated by the database so a new workspace can receive webhooks
    // without any application step.
    webhookEndpointId: text().unique().notNull()
      .default("replace(gen_random_uuid()::text, '-', '')"),
    webhookSecret:     text().notNull()
      .default("replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '')"),

    minLinkAmount:     money(),
    maxLinkAmount:     money(),

    // What this agency calls an account and an agent. Both forms are stored
    // because pluralising in code breaks on words like "staff" or "talent".
    accountLabel:       text().notNull().default("'Account'"),
    accountLabelPlural: text().notNull().default("'Accounts'"),
    agentLabel:         text().notNull().default("'Agent'"),
    agentLabelPlural:   text().notNull().default("'Agents'"),
  },
  checks: [
    'min_link_amount IS NULL OR max_link_amount IS NULL OR min_link_amount <= max_link_amount',
  ],
  indexes: ['webhookEndpointId'],
  timestamps: 'both',
});

// Effective-dated platform rate card. marginRatePct is HigherPays' own cut:
// never expose it to a workspace, which sees only the blended rate.
const PlatformFeeRate = entity('platform_fee_rates', {
  fields: {
    id:              uuid().primaryKey(),
    workspaceId:     uuid().references('workspaces').notNull(),
    feeModel:        enumOf(FEE_MODEL).notNull().default("'flat'"),
    pspRatePct:      percent().notNull(),      // combined PSP rate when mdr/settlement are null
    mdrPct:          percent(),                // processing commission, cascade model
    settlementPct:   percent(),                // settlement fee, applied after the fixed fee
    pspFixedFee:     money().notNull().default('0'),
    marginRatePct:   percent().notNull().default('0'),
    blendedRatePct:  numeric(6, 2).generatedAs('psp_rate_pct + margin_rate_pct'),
    effectiveFrom:   timestamp().notNull().default('now()'),
    createdByUserId: uuid().references('users', 'SET NULL'),
  },
  indexes: [{ columns: ['workspaceId', 'effectiveFrom'] }],
  timestamps: 'created',
});

// ===========================================================================
// Access — who may sign into a workspace
// ===========================================================================

// Access only: who may sign into this workspace, and as what. It says nothing
// about the business — an agent's rate lives on `agents`, an account's terms on
// `accounts`. A platform admin holds a row in every workspace, so creating a
// workspace must also create one for each platform admin.
const WorkspaceUser = entity('workspace_users', {
  fields: {
    workspaceId: uuid().references('workspaces').notNull(),
    userId:      uuid().references('users').notNull(),
    role:        enumOf(WORKSPACE_ROLE).notNull(),
    status:      enumOf(ACCESS_STATUS).notNull().default("'active'"),
  },
  primaryKey: ['workspaceId', 'userId'],
  // Redundant on its own — accounts and agents point at it to prove the user
  // holds the matching role in that workspace.
  unique: [['workspaceId', 'userId', 'role']],
  indexes: ['userId'],
  timestamps: 'both',
});

// A pending workspace invitation. Only the token hash is stored.
const Invite = entity('invites', {
  fields: {
    id:              uuid().primaryKey(),
    workspaceId:     uuid().references('workspaces').notNull(),
    email:           citext().notNull(),
    role:            enumOf(WORKSPACE_ROLE).notNull(),
    tokenHash:       text().unique().notNull(),
    invitedByUserId: uuid().references('users', 'SET NULL'),
    expiresAt:       timestamp().notNull(),
    acceptedAt:      timestamp(),
  },
  indexes: ['workspaceId'],
  timestamps: 'created',
});

// ===========================================================================
// Commercial structure
// ===========================================================================

// The business entity revenue is attributed to. Replaces the old "creator".
const Account = entity('accounts', {
  fields: {
    id:                uuid().primaryKey(),
    workspaceId:       uuid().references('workspaces').notNull(),
    userId:            uuid().notNull(),
    // Constant, and only here so the foreign key below can carry it: the owner
    // must hold role 'account_owner' in this same workspace.
    role:              enumOf(['account_owner']).notNull().default("'account_owner'"),
    name:              text().notNull(),   // trading name; the person's name is users.fullName
    handle:            text(),
    country:           char(2),
    status:            enumOf(ACCOUNT_STATUS).notNull().default("'active'"),
    revenueSplitPct:   percent().notNull().default('70'),
  },
  foreignKeys: [
    { columns: ['workspaceId', 'userId', 'role'], table: 'workspace_users',
      references: ['workspaceId', 'userId', 'role'], onDelete: 'RESTRICT' },
  ],
  unique: [
    ['workspaceId', 'userId'],   // one account per owner, per workspace
    ['workspaceId', 'id'],       // lets account_agents prove same-workspace
  ],
  indexes: ['workspaceId'],
  timestamps: 'both',
});

// The person who sells on behalf of accounts, and what they earn doing it.
// Their name and sign-in state come from users and workspace_users.
const Agent = entity('agents', {
  fields: {
    id:            uuid().primaryKey(),
    workspaceId:   uuid().references('workspaces').notNull(),
    userId:        uuid().notNull(),
    // Same device as accounts.role: the user must hold role 'agent' here.
    role:          enumOf(['agent']).notNull().default("'agent'"),
    country:       char(2),
    commissionPct: percent().notNull().default('0'),  // overrides revenue_rules.agentPct
  },
  foreignKeys: [
    { columns: ['workspaceId', 'userId', 'role'], table: 'workspace_users',
      references: ['workspaceId', 'userId', 'role'], onDelete: 'RESTRICT' },
  ],
  unique: [
    ['workspaceId', 'userId'],
    ['workspaceId', 'id'],
  ],
  indexes: ['workspaceId'],
  timestamps: 'both',
});

// Which agents work an account.
const AccountAgent = entity('account_agents', {
  fields: {
    workspaceId: uuid().references('workspaces').notNull(),
    accountId:   uuid().notNull(),
    agentId:     uuid().notNull(),
  },
  // Both keys carry workspaceId, so an account can only ever be joined to an
  // agent from its own workspace.
  foreignKeys: [
    { columns: ['workspaceId', 'accountId'], table: 'accounts', references: ['workspaceId', 'id'] },
    { columns: ['workspaceId', 'agentId'],   table: 'agents',   references: ['workspaceId', 'id'] },
  ],
  primaryKey: ['accountId', 'agentId'],
  indexes: ['agentId'],
});

// The sale categories one workspace defines. An agent picks one when
// completing a paid payment.
const Category = entity('categories', {
  fields: {
    id:          uuid().primaryKey(),
    workspaceId: uuid().references('workspaces').notNull(),
    name:        text().notNull(),
    active:      bool().notNull().default('true'),
  },
  unique: [['workspaceId', 'name']],
  timestamps: 'created',
});

// The payer. deletedAt is a soft delete for erasure requests.
const Customer = entity('customers', {
  fields: {
    id:             uuid().primaryKey(),
    workspaceId:    uuid().references('workspaces').notNull(),

    name:           text().notNull(),
    telegramName:   text(),           // the Telegram initiator, entered by the agent
    email:          citext(),
    phone:          text(),
    country:        char(2),
    segment:        enumOf(CUSTOMER_SEGMENT).notNull().default("'new'"),
    totalSpend:     money().notNull().default('0'),   // cached, recomputed on payment
    lastPurchaseAt: timestamp(),
    deletedAt:      timestamp(),
  },
  indexes: ['workspaceId', { columns: ['workspaceId', 'segment'] }],
  timestamps: 'both',
});

// ===========================================================================
// Payment flow: link -> payment -> transaction
// ===========================================================================

// The payment page. MantaPay hosts the checkout; we store the reference it
// returns. No card data ever reaches this database.
const PaymentLink = entity('payment_links', {
  fields: {
    id:                    uuid().primaryKey(),
    workspaceId:           uuid().references('workspaces').notNull(),
    accountId:             uuid().references('accounts', 'RESTRICT').notNull(),
    customerId:            uuid().references('customers', 'SET NULL'),
    createdByAgentId:      uuid().references('agents', 'SET NULL'),      // the attributed agent
    description:           text(),
    type:                  enumOf(LINK_TYPE).notNull(),
    pricingMode:           enumOf(PRICING_MODE).notNull().default("'fixed'"),
    amount:                money(),             // null when the payer chooses the amount
    currency:              char(3).notNull(),
    status:                enumOf(LINK_STATUS).notNull().default("'active'"),
    referenceId:           text(),              // our reference, sent to the provider
    providerRequestId:     text(),              // provider's id for the create-link call
    providerLinkId:        text(),
    checkoutUrl:           text(),
    expiresAt:             timestamp(),   // single_use only, set to creation + 24h
    paidAt:                timestamp(),   // single_use only; reusable links read payments
  },
  checks: [
    "pricing_mode = 'open' OR (amount IS NOT NULL AND amount > 0)",
    "type = 'single_use' OR (expires_at IS NULL AND paid_at IS NULL)",
  ],
  indexes: [
    'workspaceId', 'accountId', 'customerId',
    { columns: ['workspaceId', 'status'] },
    { columns: ['workspaceId', 'referenceId'], unique: true, where: 'reference_id IS NOT NULL' },
  ],
  timestamps: 'both',
});

// One checkout attempt by a payer. The business event; a reusable link has
// many. Attribution lives here, so transactions need not repeat it.
const Payment = entity('payments', {
  fields: {
    id:                uuid().primaryKey(),
    workspaceId:       uuid().references('workspaces').notNull(),
    accountId:         uuid().references('accounts', 'RESTRICT').notNull(),
    paymentLinkId:     uuid().references('payment_links', 'SET NULL'),
    customerId:        uuid().references('customers', 'SET NULL'),   // set by the agent, or by the PSP when it identifies one
    categoryId:        uuid().references('categories', 'SET NULL'),  // chosen by the agent after payment
    agentId:           uuid().references('agents', 'SET NULL'),
    amount:            money().notNull(),
    currency:          char(3).notNull(),
    status:            enumOf(PAYMENT_STATUS).notNull(),   // always written with the provider's outcome
    paymentMethod:     text(),                  // when the provider reports it
    providerPaymentId: text(),
    occurredAt:        timestamp().notNull().default('now()'),
  },
  unique: [['workspaceId', 'providerPaymentId']],
  indexes: [
    'workspaceId', 'accountId', 'paymentLinkId',
    { columns: ['workspaceId', 'occurredAt'] },
  ],
  timestamps: 'both',
});

// One money movement at the provider. A payment may have several: the sale,
// then a refund or chargeback. This is the ledger's input.
const Transaction = entity('transactions', {
  fields: {
    id:                    uuid().primaryKey(),
    workspaceId:           uuid().references('workspaces').notNull(),
    paymentId:             uuid().references('payments', 'RESTRICT').notNull(),
    type:                  enumOf(TRANSACTION_TYPE).notNull().default("'payment'"),
    status:                enumOf(TRANSACTION_STATUS).notNull(),
    gross:                 money().notNull().default('0'),
    fee:                   money().notNull().default('0'),   // the actual PSP fee, when reported
    surcharge:             money().notNull().default('0'),
    net:                   money().notNull().default('0'),
    currency:              char(3).notNull(),
    providerTransactionId: text(),
    occurredAt:            timestamp().notNull().default('now()'),
    rawPayload:            jsonb(),
  },
  unique: [['workspaceId', 'providerTransactionId']],
  indexes: [
    'workspaceId', 'paymentId',
    { columns: ['workspaceId', 'occurredAt'] },
  ],
  timestamps: 'created',
});

// ===========================================================================
// Revenue: how a transaction is split, and what gets paid out
// ===========================================================================

// Effective-dated split rules. accountId null is the workspace default.
const RevenueRule = entity('revenue_rules', {
  fields: {
    id:              uuid().primaryKey(),
    workspaceId:     uuid().references('workspaces').notNull(),
    accountId:       uuid().references('accounts'),
    accountSplitPct: percent().notNull(),
    agencySplitPct:  percent().notNull(),
    agentPct:        percent().notNull().default('0'),
    effectiveFrom:   timestamp().notNull().default('now()'),
    createdByUserId: uuid().references('users', 'SET NULL'),
  },
  indexes: [{ columns: ['workspaceId', 'effectiveFrom'] }],
  timestamps: 'created',
});

// The split of one transaction, written once and never edited. A reversal is
// a new entry, which is why amounts carry four decimals: no rounding drift.
const RevenueEntry = entity('revenue_entries', {
  fields: {
    id:                uuid().primaryKey(),
    workspaceId:       uuid().references('workspaces').notNull(),
    transactionId:     uuid().references('transactions').notNull(),
    accountId:         uuid().references('accounts', 'SET NULL'),
    agentId:           uuid().references('agents', 'SET NULL'),
    entryType:         enumOf(REVENUE_ENTRY_TYPE).notNull(),
    status:            enumOf(REVENUE_ENTRY_STATUS).notNull().default("'locked'"),

    gross:             numeric(14, 4).notNull(),
    platformFee:       numeric(14, 4).notNull(),   // blended, what the agency is charged
    platformMargin:    numeric(14, 4).notNull(),   // HigherPays' cut
    pspFee:            numeric(14, 4).notNull(),   // actual when reported, else expected
    distributable:     numeric(14, 4).notNull(),
    accountAmount:     numeric(14, 4).notNull(),
    agentAmount:       numeric(14, 4).notNull(),
    agencyAmount:      numeric(14, 4).notNull(),

    feeMdr:            numeric(14, 4).notNull().default('0'),
    feeFixed:          numeric(14, 4).notNull().default('0'),
    feeSettlement:     numeric(14, 4).notNull().default('0'),
    feeSurcharge:      numeric(14, 4).notNull().default('0'),
    chargebackFee:     numeric(14, 4).notNull().default('0'),

    accountPayoutId:   uuid().references('payouts', 'SET NULL'),
    agentPayoutId:     uuid().references('payouts', 'SET NULL'),
    accountPaidAt:     timestamp(),
    agentPaidAt:       timestamp(),
  },
  indexes: ['workspaceId', 'transactionId', 'accountId'],
  timestamps: 'created',
});

// What one payee is owed for one period.
const Payout = entity('payouts', {
  fields: {
    id:           uuid().primaryKey(),
    workspaceId:  uuid().references('workspaces').notNull(),
    payeeType:    enumOf(PAYEE_TYPE).notNull(),
    accountId:    uuid().references('accounts', 'SET NULL'),
    agentId:      uuid().references('agents', 'SET NULL'),
    periodStart:  date().notNull(),
    periodEnd:    date().notNull(),
    gross:        money().notNull().default('0'),
    fees:         money().notNull().default('0'),
    refunds:      money().notNull().default('0'),
    net:          money().notNull().default('0'),   // what is actually paid
    currency:     char(3).notNull(),
    status:       enumOf(PAYOUT_STATUS).notNull().default("'pending'"),
  },
  indexes: [{ columns: ['workspaceId', 'periodStart'] }],
  timestamps: 'both',
});

// ===========================================================================
// Settlement with the provider
// ===========================================================================

// Effective-dated per-event fees the PSP charges on settlement. Set by the
// platform, not by the workspace.
const SettlementFeeConfig = entity('settlement_fee_config', {
  fields: {
    id:                 uuid().primaryKey(),
    workspaceId:        uuid().references('workspaces').notNull(),
    chargebackFee:      money().notNull().default('0'),
    refundFee:          money().notNull().default('0'),
    declineFee:         money().notNull().default('0'),
    settlementFeePct:   percent().notNull().default('0'),
    settlementFeeFlat:  money().notNull().default('0'),
    reservePct:         percent().notNull().default('0'),
    reserveReleaseDays: int().notNull().default('0'),
    effectiveFrom:      timestamp().notNull().default('now()'),
    createdByUserId:    uuid().references('users', 'SET NULL'),
  },
  indexes: [{ columns: ['workspaceId', 'effectiveFrom'] }],
  timestamps: 'created',
});

// One settlement report from the provider, imported as-is. Four decimals
// because the provider's own figures carry them.
const Settlement = entity('settlements', {
  fields: {
    id:                uuid().primaryKey(),
    workspaceId:       uuid().references('workspaces').notNull(),
    currency:          char(3).notNull(),
    periodStart:       date().notNull(),
    periodEnd:         date().notNull(),
    settlementDate:    date(),
    paid:              bool().notNull().default('false'),

    totalTransactions: int().notNull().default('0'),
    refunds:           int().notNull().default('0'),
    chargebacks:       int().notNull().default('0'),
    declined:          int().notNull().default('0'),

    volume:            numeric(16, 4).notNull().default('0'),
    approvedCost:      numeric(16, 4).notNull().default('0'),
    declineCost:       numeric(16, 4).notNull().default('0'),
    refundCost:        numeric(16, 4).notNull().default('0'),
    chargebackCost:    numeric(16, 4).notNull().default('0'),
    mdr:               numeric(16, 4).notNull().default('0'),
    volumeFee:         numeric(16, 4).notNull().default('0'),
    reserve:           numeric(16, 4).notNull().default('0'),   // held this period
    totalFees:         numeric(16, 4).notNull().default('0'),
    net:               numeric(16, 4).notNull().default('0'),
    debit:             numeric(16, 4).notNull().default('0'),   // carried forward
    credit:            numeric(16, 4).notNull().default('0'),   // due to be paid out

    reportSettings:    jsonb(),                 // fee rates printed in the report header
    sourceFile:        text(),
    importedByUserId:  uuid().references('users', 'SET NULL'),
    importedAt:        timestamp().notNull().default('now()'),
  },
  unique: [['workspaceId', 'currency', 'periodStart', 'periodEnd']],
  indexes: ['workspaceId'],
});

// ===========================================================================
// Operations
// ===========================================================================

// One in-app event. accountId and agentId narrow who should see it.
const Notification = entity('notifications', {
  fields: {
    id:                uuid().primaryKey(),
    workspaceId:       uuid().references('workspaces').notNull(),
    event:             text().notNull(),        // e.g. 'payment.paid'
    title:             text().notNull(),
    body:              text(),
    amount:            money(),
    currency:          char(3),
    entityType:        text(),
    entityId:          uuid(),
    accountId:         uuid().references('accounts', 'SET NULL'),
    agentId:           uuid().references('agents', 'SET NULL'),
  },
  indexes: [{ columns: ['workspaceId', 'createdAt'] }],
  timestamps: 'created',
});

const NotificationRead = entity('notification_reads', {
  fields: {
    workspaceId:    uuid().references('workspaces').notNull(),
    notificationId: uuid().references('notifications').notNull(),
    userId:         uuid().references('users').notNull(),
    readAt:         timestamp().notNull().default('now()'),
  },
  primaryKey: ['notificationId', 'userId'],
});

// Where a workspace forwards events outside the app.
const NotificationChannel = entity('notification_channels', {
  fields: {
    id:              uuid().primaryKey(),
    workspaceId:     uuid().references('workspaces').notNull(),
    type:            enumOf(CHANNEL_TYPE).notNull(),
    target:          text().notNull(),          // chat id, for telegram
    label:           text(),
    events:          textArray().notNull().default("ARRAY['payment.paid']"),
    active:          bool().notNull().default('true'),
    lastError:       text(),
    lastSentAt:      timestamp(),
    createdByUserId: uuid().references('users', 'SET NULL'),
  },
  unique: [['workspaceId', 'type', 'target']],
  timestamps: 'created',
});

// Which events one user wants, in one workspace.
const NotificationPreference = entity('notification_preferences', {
  fields: {
    workspaceId: uuid().references('workspaces').notNull(),
    userId:      uuid().references('users').notNull(),
    events:      textArray().notNull()
      .default("ARRAY['payment.paid','payment.failed','payment.refunded','payment.chargeback','payout.paid']"),
    updatedAt:   timestamp().notNull().default('now()'),
  },
  primaryKey: ['workspaceId', 'userId'],
});

// Idempotent inbox for provider callbacks. workspaceId is null until the
// payload is resolved to a workspace.
const WebhookEvent = entity('webhook_events', {
  fields: {
    id:              uuid().primaryKey(),
    workspaceId:     uuid().references('workspaces', 'SET NULL'),
    provider:        text().notNull(),
    eventType:       text(),
    providerEventId: text(),
    signatureValid:  bool(),
    processed:       bool().notNull().default('false'),
    payload:         jsonb().notNull(),
    receivedAt:      timestamp().notNull().default('now()'),
    processedAt:     timestamp(),
  },
  unique: [['provider', 'providerEventId']],
  indexes: [{ columns: ['processed'], where: 'processed = false' }],
});

// Append-only record of actions and PII access.
const AuditLog = entity('audit_log', {
  fields: {
    id:          bigIdentity(),
    workspaceId: uuid().references('workspaces', 'SET NULL'),
    actorUserId: uuid().references('users', 'SET NULL'),
    action:      text().notNull(),              // e.g. 'customer.export', 'link.create'
    entityType:  text(),
    entityId:    uuid(),
    metadata:    jsonb().notNull().default("'{}'::jsonb"),
    ip:          inet(),
  },
  indexes: [
    { columns: ['workspaceId', 'createdAt'] },
    { columns: ['actorUserId', 'createdAt'] },
  ],
  timestamps: 'created',
});

module.exports = {
  // global
  User, RefreshToken, Workspace, PlatformFeeRate,
  // access
  WorkspaceUser, Invite,
  // commercial
  Account, Agent, AccountAgent, Category, Customer,
  // payment flow
  PaymentLink, Payment, Transaction,
  // revenue
  RevenueRule, RevenueEntry, Payout,
  // settlement
  SettlementFeeConfig, Settlement,
  // operations
  Notification, NotificationRead, NotificationChannel,
  NotificationPreference, WebhookEvent, AuditLog,

  status: {
    USER_STATUS, WORKSPACE_STATUS, WORKSPACE_ROLE, ACCESS_STATUS,
    ACCOUNT_STATUS, CUSTOMER_SEGMENT, PRICING_MODE,
    LINK_TYPE, LINK_STATUS,
    PAYMENT_STATUS, TRANSACTION_TYPE, TRANSACTION_STATUS, REVENUE_ENTRY_TYPE,
    REVENUE_ENTRY_STATUS, PAYEE_TYPE, PAYOUT_STATUS, FEE_MODEL, CHANNEL_TYPE,
  },
};
